### PR TITLE
Allow for a less specific PSR log version

### PR DESCRIPTION
**Pull request by johmanx10**
The update allows for more recent patch versions of PSR Log to be installed.

### CODE REVIEW

**Comment by cirnatdan** [comment]
Would help me a lot to get this merged, it's a simple improvement

**Comment by kleijnweb** [comment]
@cirnatdan I have not merged it because the build failed, and there was no follow up.

**Comment by johmanx10** [comment]
@kleijnweb the build failed for code changes outside of this pull request and will still fail if the single character in the version constraints that was added is reverted again. The failing build has got nothing to do with the requested change. If you look at the diff you can verify this to be true. There has been no follow up because I did not foresee one would expect me to fix a massive chunk of failing code or tests, simply because I loosened the version constraint on a package that has no influence on the fails.

**Comment by kleijnweb** [comment]
Turns out there are some issues in the hydrator and api-description dependencies which I'll have a look at.

**Comment by johmanx10** [comment]
@kleijnweb we have long since moved on to a different solution and only kept this open as a courtesy gesture. I close this pull request knowing you'll be able to patch this single character in the version constraint once more, when you take a look at the other dependencies.

**Comment by kleijnweb** [comment]
FYI, those issues were fixed and the constrained loosened.

**Pull request closed without merging**
