### PR TITLE
Fix symfony 3.3+ compatibility

### PR DESCRIPTION
**Pull request by Darkrulerz**
Revert 731503b30b6ced69db77223ed0a057a9a2b3e9ae and implement an alternative

Had to update fr3d/swagger-assertions. Didn't update to the latest to keep compatibility with PHP 5.5/5.6

### CODE REVIEW

**Comment by kleijnweb** [comment]
This breaks 5.4 though, which is still the default on centos 7:

```
$ docker run --rm centos:7 bash -c 'yum install -y php 2&>/dev/null && php -v'
PHP 5.4.16 (cli) (built: Mar  7 2018 13:34:47) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
```
Is it somehow possible to get both Symfony 3.3 support and php 5.4 compatibility?

**Comment by kleijnweb** [comment]
@Darkrulerz Travis still fails when running composer install with --prefer-lowest

**Comment by Darkrulerz** [comment]
@kleijnweb Should be good now right? ;)

**Comment by kleijnweb** [comment]
Should be fine, thanks :)

**Pull request merged**
